### ISSUE TITLE
Meetup Creation Screen

### ISSUE THREAD

**Issue by harryslimes** [project-accelerate/m.app#61]

**Comment by conatus** [comment]
# TODO

## Frontend

### Meetup Host

- [ ] Get the basic form working with Formik.
  - [ ] Where does the email currently save to if the person says save?
  - [ ] Name
  - [ ] Email (if we don't have it earlier in the application)
  - [ ] Telephone number (if we don't have it earlier in the application)
- [ ] Boot up the Storybook for the page as a whole to develop against.
- [ ] Move form over to using `Wizard` component for multiple stages.
- [ ] Write some tests.

### Meetup Guest

- [ ] Once approved event can be seen in events list - under a new tab?
- [ ] Guest can attend event and it saves to their calendar as with other events.

## Backend

- [ ] New migration for adding the meetups table.
- [ ] New mutation to allow submission of events by regular user. There is going to have to be auth around this.
- [ ] New query to query just user created events.

**Comment by conatus** [comment]
Further niceities:
- [ ] Make a generic form component that wraps with errors.

**Comment by conatus** [comment]
# Moderation

- `MeetupModerationQueue` switches `isApproved` to `true`.
- There is a meetups query endpoint that returns meetups that are approved as `Event` type.
- There is a meetups list in the app that displays meetups and they can be interacted with as any other `Event` can be.
